{{ if false }}
{{ if .Values.kafka_exporter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  labels:
    app.kubernetes.io/instance: kafka-exporter
    app.kubernetes.io/name: kafka-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: kafka-exporter
      app.kubernetes.io/name: kafka-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: kafka-exporter
        app.kubernetes.io/name: kafka-exporter
    spec:
      containers:
      - name: exporter
        image: danielqsj/kafka-exporter
        ports:
        - containerPort: 9308
          name: http
        args:
          - --kafka.server={{ .Values.kafka_exporter.broker }}
          - --kafka.version=1.0.0
          {{ if .Values.kafka_exporter.sasl.enabled }}
          - --sasl.enabled
          - --sasl.username={{ .Values.kafka_exporter.sasl.username }}
          - --sasl.password={{ .Values.kafka_exporter.sasl.password }}
          - --sasl.mechanism=PLAIN
          {{ end }}
          {{ if .Values.kafka_exporter.tls.enabled }}
          - --tls.enabled
          - --tls.insecure-skip-tls-verify      
          {{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
  labels:
    app.kubernetes.io/instance: kafka-exporter
    app.kubernetes.io/name: kafka-exporter
    scrape-prometheus: "true"
spec:
  type: ClusterIP
  ports:
    - port: 9308
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/instance: kafka-exporter
    app.kubernetes.io/name: kafka-exporter
{{ end }}
{{ end }}