apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation
  labels:
    {{include "common.labels" "recommendation" | nindent 4}}
spec:
  replicas: 2
  selector:
    matchLabels:
      {{include "common.labels" "recommendation" | nindent 6}}
  template:
    metadata:
      labels:
        {{include "common.labels" "recommendation" | nindent 8}}
    spec:
      containers: 
      {{include "chaosmania.container" . | nindent 6}}
      volumes:
      {{include "common.volumes" . | nindent 6}}
---
{{include "chaosmania.service" "recommendation"}}
---
{{ if .Values.hpa.enabled }}
{{ include "chaosmania.hpa" "recommendation" }}
{{ end }}
