apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "client.fullname" .}}-plans
data:
{{- range $path, $_ :=  .Files.Glob .Values.chaos.plans }}
{{ $path | trimPrefix "plans/"  | indent 2 }}: |-
{{ $.Files.Get $path | indent 4 }}
{{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "client.fullname" .}}-scenarios
data:
{{- range $path, $_ :=  .Files.Glob .Values.chaos.scenarios }}
{{ $path | trimPrefix "scenarios/" | replace "/" "-" | indent 2 }}: |-
{{ $.Files.Get $path | indent 4 }}
{{ end }}