apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "single.fullname" . }}
  labels:
    {{- include "single.labels" . | nindent 4}}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "single.selectorLabels" . | nindent 6}}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "single.labels" . | nindent 8}}
    spec:
      securityContext:
        fsGroup: 2000
      {{- if .Values.nodeName }}
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.nodeName }}
      {{ end }}
      dnsConfig:
        options:
          - name: ndots
            value: "{{ .Values.ndots }}"
      containers:
      {{- include "chaosmania.container" . | nindent 8}}
      volumes:
        {{ if .Values.persistence.enabled }}
        - name: repository
          persistentVolumeClaim:
              claimName: data 
        {{ end }}
