apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "single.fullname" . }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Values.business_application }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/part-of: {{ .Values.business_application }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/part-of: {{ .Values.business_application }}
    spec:
      securityContext:
        fsGroup: 2000
      {{- if .Values.nodeName }}
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.nodeName }}
      {{ end }}
      dnsConfig:
        options:
          - name: ndots
            value: "{{ .Values.ndots }}"
      containers:
      {{- include "chaosmania.container" . | nindent 8}}
      volumes:
        {{ if .Values.persistence.enabled }}
        - name: repository
          persistentVolumeClaim:
              claimName: data 
        {{ end }}
