kind: Secret
apiVersion: v1
metadata:
  name: {{ include "single.fullname" . }}-services
stringData:
  services.yaml: |
    services: 
{{ toYaml .Values.services | indent 6 }}
  background_services.yaml: |
    services: 
{{ toYaml .Values.background_services | indent 6 }}