apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Values.business_application }}
    scrape-prometheus: "true"
    {{ if hasKey .Values "thresholds" }}
    {{ if hasKey .Values.thresholds "error_rate" }}
    causely.ai/error-rate-threshold: "{{ .Values.thresholds.error_rate }}"
    {{ end }}
    {{ if hasKey .Values.thresholds "latency" }}
    causely.ai/latency-threshold: "{{ .Values.thresholds.latency }}"
    {{ end }}
    {{ end }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}