{{- if  .Capabilities.APIVersions.Has "monitoring.coreos.com/v1"  }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "single.fullname" . }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Values.business_application }}
spec:
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
  jobLabel: chaosmania
  selector:
    matchLabels:
      scrape-prometheus: "true"
{{- end }}