apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction
  labels:
    {{include "common.labels" "transaction" | nindent 4}}
spec:
  selector:
    matchLabels:
      {{include "common.labels" "transaction" | nindent 6}}
  template:
    metadata:
      labels:
        {{include "common.labels" "transaction" | nindent 8}}
    spec:
      containers: 
      {{include "chaosmania.container" . | nindent 6}}
      volumes:
      {{include "common.volumes" . | nindent 6}}
---
{{include "chaosmania.service" "transaction"}}
