apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad
  labels:
    app.kubernetes.io/instance: ad
    app.kubernetes.io/name: ad
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: ad
      app.kubernetes.io/name: ad
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: ad
        app.kubernetes.io/name: ad
    spec:
      containers: 
      {{include "chaosmania.container" . | nindent 6}}
---
{{include "chaosmania.service" "ad"}}
