apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  labels:
    app.kubernetes.io/instance: cart
    app.kubernetes.io/name: cart
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: cart
      app.kubernetes.io/name: cart
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: cart
        app.kubernetes.io/name: cart
    spec:
      containers:
      {{include "chaosmania.container" . | nindent 6}}
---
{{ include "chaosmania.service" "cart" }}