apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency
  labels:
    app.kubernetes.io/instance: currency
    app.kubernetes.io/name: currency
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: currency
      app.kubernetes.io/name: currency
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: currency
        app.kubernetes.io/name: currency
    spec:
      containers: 
      {{include "chaosmania.container" . | nindent 6}}
---
{{ include "chaosmania.service" "currency" }}