apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalog
  labels:
    {{include "common.labels" "productcatalog" | nindent 4}}
spec:
  selector:
    matchLabels:
      {{include "common.labels" "productcatalog" | nindent 6}}
  template:
    metadata:
      labels:
        {{include "common.labels" "productcatalog" | nindent 8}}
    spec:
      containers:
      {{include "chaosmania.container" . | nindent 8}}
      volumes:
      {{include "common.volumes" . | nindent 6}}
---
{{ include "chaosmania.service" "productcatalog" }}