apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalog
  labels:
    app.kubernetes.io/instance: productcatalog
    app.kubernetes.io/name: productcatalog
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: productcatalog
      app.kubernetes.io/name: productcatalog
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: productcatalog
        app.kubernetes.io/name: productcatalog
    spec:
      containers:
      {{include "chaosmania.container" . | nindent 8}}
---
{{ include "chaosmania.service" "productcatalog" }}