apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation
  labels:
    app.kubernetes.io/instance: recommendation
    app.kubernetes.io/name: recommendation
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: recommendation
      app.kubernetes.io/name: recommendation
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: recommendation
        app.kubernetes.io/name: recommendation
    spec:
      containers:
      {{include "chaosmania.container" . | nindent 8}}
---
{{ include "chaosmania.service" "recommendation" }}