---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app.kubernetes.io/instance: redis
    app.kubernetes.io/name: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      name: redis
      targetPort: redis
  selector:
    app.kubernetes.io/instance: redis
    app.kubernetes.io/name: redis
