apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    app: shipping
spec:
  selector:
    matchLabels:
      app: shipping
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
      {{- include "chaosmania.container" . | nindent 6}}
---
{{ include "chaosmania.service" "shipping" }}