primary:
  service:
    annotations:
      causely.ai/latency-threshold: "100.0"

  extendedConfiguration: |
    shared_preload_libraries = 'pg_stat_statements'
    pg_stat_statements.max = 10000
    pg_stat_statements.track = top
    pg_stat_statements.save = on
    pg_stat_statements.track_utility = on
    track_io_timing = on