image:
  repository: quay.io/causely/chaosmania
  pullPolicy: Always
  tag: "latest"

resources:
  # limits:
  #    cpu: 100m
  #    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

business_application: "chaosmania"

chaos:
  plan: "/plans/boutique.yaml"
  host: "single"
  port: "8080"
  plans: "plans/*.yaml"
  scenarios: "scenarios/**.yaml"
  header: ""
  pattern-duration: None   # 1h, 30m, 10m, 5m, 1m, 30s, 10s, 5s, 1s
  phase-pattern: None      # sequence, cycle, random
  repeats-per-phase: None  # 0 for unlimited, max 500

otlp:
  enabled: false
  endpoint: http://alloy.monitoring:4318
  insecure: true
