image:
  repository: quay.io/causely/chaosmania
  pullPolicy: Always
  tag: "latest"

resources:
  # limits:
  #    cpu: 100m
  #    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

business_application: "chaosmania"

chaos:
  plan: "/plans/boutique.yaml"
  host: "single"
  port: "8080"
  plans: "plans/*.yaml"
  scenarios: "scenarios/**.yaml"