---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      name: postgres
      targetPort: postgres
  selector:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgres
