{{- if and ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) ( .Values.serviceMonitor.enabled ) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trading
spec:
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
  jobLabel: trading
  selector:
    matchLabels:
      scrape-prometheus: "true"
{{- end }}
