image:
  repository: quay.io/causely/chaosmania
  pullPolicy: Always
  tag: "latest"

ndots: 5

persistence:
  enabled: false
  size: 11Gi
#  storageClass:

business_application: "single"

#nodeName:

resources:
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

replicaCount: 1

securityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
  allowPrivilegeEscalation: false
  privileged: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
    - all

otlp:
  endpoint: "" # http://tempo.monitoring:4318
  insecure: true
