image:
  repository: quay.io/causely/chaosmania
  pullPolicy: Always
  tag: "latest"

resources:
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

replicaCount: 1

securityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
  allowPrivilegeEscalation: false
  privileged: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
    - all
    add: ['NET_BIND_SERVICE']

otlp:
  endpoint: "" # http://tempo.monitoring:4318
  insecure: true
