image:
  repository: quay.io/causely/chaosmania
  pullPolicy: Always
  tag: "latest"

ndots: 5

persistence:
  enabled: false
  size: 11Gi
#  storageClass:

business_application: "chaosmania"
nodeName: 

resources:
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

replicaCount: 1

securityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
  allowPrivilegeEscalation: false
  privileged: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
    - all

otlp:
  enabled: false
  endpoint: http://alloy.monitoring:4318
  insecure: true

datadog:
  enabled: false

services:
  # - name: "kafka-producer"
  #   type: kafka-producer
  #   config:
  #     peer_service: kafka
  #     peer_namespace: chaosmania
  #     brokers:
  #       - "" # TODO
  #     username: "" # TODO
  #     password: "" # TODO
  #     tls_enable: false
  #     sasl_enable: false

background_services:
  # - name: "kafka-consumer"
  #   type: kafka-consumer
  #   config:
  #     peer_service: kafka
  #     peer_namespace: chaosmania
  #     brokers:
  #       - "" # TODO
  #     username: "" # TODO
  #     password: "" # TODO
  #     tls_enable: true
  #     sasl_enable: true
  #     topic: test1
  #     group: my-consumer-group
  #     script: |
  #       function run() {
  #         var msg = ctx.get_message();
  #         ctx.print("Received message: " + msg);
  #       }

enabled_background_services: []