name: Build & Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags-ignore:
      - "**"

jobs:
  test:
    uses: causely-oss/chaosmania/.github/workflows/test.yaml@main

  build-images:
    needs: test
    uses: causely-oss/chaosmania/.github/workflows/build.yaml@main
    secrets: inherit
