name: Release

on:
  push:
    tags:
      - "*"

jobs:
  test:
    uses: causely-oss/chaosmania/.github/workflows/test.yaml@main

  build-images:
    needs: test
    uses: causely-oss/chaosmania/.github/workflows/build.yaml@main
    secrets: inherit
    with:
      push: true
